### ISSUE TITLE
Добавить подсчет затрат на использование

### ISSUE THREAD

**Issue by hteppl** [vasia123/farm-world-space-calculator#1]
Было бы неплохо не просто умножать ресурсы на их цену, а еще и считать сколько требуется мяса и золота на восстановление показателей.

**Comment by avanturist888** [comment]
Хорошая идея! В ближайшее время сделаю.

**Comment by hteppl** [comment]
> Хорошая идея! В ближайшее время сделаю.

Спасибо, а то выходит что окупаемость неправильно считается, меньше в несколько раз, чем есть на самом деле.

**Comment by avanturist888** [comment]
> Спасибо, а то выходит что окупаемость неправильно считается, меньше в несколько раз, чем есть на самом деле.

Не. Под капотом всё верно считается - нет только вывода для людей. Можешь сам проверить:
![image](https://github.com/vasia123/farm-world-space-calculator/assets/801823/b3cf480a-61b2-49bc-85b2-76847864b455)

**Comment by avanturist888** [comment]
Добавил столбец расходов ресурсов
