### ISSUE TITLE
Потребление памяти

### ISSUE THREAD

**Issue by hteppl** [vasia123/farm-world-space-calculator#3]
В процессе работы фронта начинается утечка памяти, хром постоянно орет что занято очень много ОЗУ (если оставить на день, то потребление доходит до 8ГБ).

![image](https://github.com/vasia123/farm-world-space-calculator/assets/34367447/7f0a8738-726b-4386-940c-2b6bfa876757)
![image](https://github.com/vasia123/farm-world-space-calculator/assets/34367447/60313915-a2e4-4626-bf84-0c125716be43)

**Comment by avanturist888** [comment]
Нашел неиспользуемую переменную которая росла безконтрольно. Отпишись если в дальнейшем такое будет происходить.

**Comment by hteppl** [comment]
> Нашел неиспользуемую переменную которая росла безконтрольно. Отпишись если в дальнейшем такое будет происходить.

Какой ты хороший разработчик, спасибо что отвечаешь быстро).

**Comment by avanturist888** [comment]
Решил проблему на корню - теперь страница будет перезагружаться каждые полчаса.
